airports:
     arrivalairports : ['MST','EIN','AMS']
     departureairports : ['GRO']


dates:
     fromdate: 2018-04-17
     todate: 2018-08-25
     duration : [2,3,4,5]
     weekdaydeparture : [4,3]
     weekdayreturn : [6,7]
